title: practice Note
# remote_theme: Frieda-Chen/rc-workshop-template
remote_theme: pmarsceill/just-the-docs
# theme: "just-the-docs"
search_enabled: true
github_repo_url: "https://github.com/frieda18/practice_note"

# Enable or disable heading anchors
heading_anchors: true

aux_links:
  "View on github":
    - "https://github.com/frieda18/practice_note"

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
